name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: '20.19.3'

    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2 instance public DNS/IP
        username: ${{ secrets.EC2_USERNAME }}  # SSH username
        key: ${{ secrets.KEY }}  # SSH private key
        script: |
          # Install Node.js if missing
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

          # Navigate to the project folder
          cd fundcirkle

          # Initialize and update the repository
          if [ ! -d ".git" ]; then
            git init
          fi

          # Reset and clean repo before pulling
          git reset --hard
          git fetch origin
          git checkout main || git checkout -b main
          git pull https://github.com/Ochaworldwide/fundcirkle.git main


          # Install dependencies and build
          npm install
          npm run build



          echo "Deploy successful"

